spring:
     datasource:
       url: jdbc:mysql://localhost:3306/testdb
       password: Hanmant@1997
       username: root
       driver-class-name: com.mysql.cj.jdbc.Driver
     jpa:
      show-sql: true
      hibernate:
       ddl-auto: update
      properties:
       dialect: org.hibernate.Dilaect.MYSQL8Dialect
       
server:
   port: 8081     
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
         

---   
spring:
  application:
    name: EurekaServer           
       
   
         
       
