spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demoex
    password: Hanmant@1997
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true  
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MYSQL8Dialect
server:
  port: 8088
management:
  endpoints:
    web:
      exposure:
        include: "*"          