spring:
  
  datasource:
    url: jdbc:mysql://localhost:3306/temple
    password: Hanmant@1997
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
       dialect: org.hibernate.dialect.MYSQL8Dialect  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true        
       
server:
  port: 8081  
  
  
logging:
  file:
    path: d:/
debug: true           