spring:
 datasource:
   url: jdbc:mysql://localhost:3306/new
   password: Hanmant@1997
   username: root
   driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
   show-sql: true
   hibernate:
      ddl-auto: update
   properties:
     dilaect: org.hibernate.dialect.MYSQL8Dilaect
server:
  port: 8081        
        